# Generated by Django 4.1 on 2022-09-20 22:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mymovie', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='noticetab',
            name='mail',
        ),
    ]
