# Generated by Django 4.1 on 2022-09-19 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="MyqnaQna",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=20)),
                ("passwd", models.CharField(max_length=20)),
                ("mail", models.CharField(max_length=30)),
                ("title", models.CharField(max_length=100)),
                ("cont", models.TextField()),
                ("bip", models.CharField(max_length=39)),
                ("bdate", models.DateTimeField()),
                ("readcnt", models.IntegerField()),
                ("gnum", models.IntegerField()),
                ("onum", models.IntegerField()),
                ("nested", models.IntegerField()),
            ],
        ),
    ]
